### ISSUE TITLE
Event.maxParticipants ignored during Participant creation

### ISSUE THREAD

**Issue by SbgMartin** [sapmentors/SITreg#18] opened 2016-08-31 18:44 UTC
Hi, 
within the database procedure com.sap.sapmentors.sitreg.odataparticipant.procedures::ParticipantCreate an additional validation has to be placed.
Before the INSERT happens there should be a SELECT on entity Event in order to retrieve the maxParticipant value. If this is already exceeded no reservation should be possible.

At the moment it's possible to book more Participants than this value.

**Comment by chtcil** [comment] 2016-09-01 15:51
Hi,
Will use the Participant.RSVP field filled with 'W' for waiting when Event-Participant count > Event-MaxParticipants, this gives the opportunity to reuse the field without the need for a DB Migration (append in the DB structure) and possible data loss..

**Comment by RenaldWittwer** [comment] 2016-09-01 17:58
Hi,
in the registration tool for SITHH we handle this a little different. That doesn't mean, that we should do it in the same way, but perhaps we can take the best from it.

First we don't show the internal ID in the participant list but an own counter. That makes clear how many places are filled.

<img width="1184" alt="bildschirmfoto 2016-09-01 um 19 50 05" src="https://cloud.githubusercontent.com/assets/9741328/18178246/def27416-707d-11e6-86be-1c51ece42923.png">

Second we show two table views, one with the participants and a second with the waiting list. It must be more than clear for the user, that he is registered but on the waiting list. The used approach is one way. Another would be to mark the lines with a different background color.

<img width="436" alt="bildschirmfoto 2016-09-01 um 19 50 24" src="https://cloud.githubusercontent.com/assets/9741328/18178365/58bc40b0-707e-11e6-8efb-d349e2294b0c.png">

**Comment by chtcil** [comment] 2016-09-01 18:27
Hi Renald,

Cool thx for the hint, this looks like a much nicer solution! Thing is, i am not 100% firm with HANAXS and this would be the least invasive way without a DB migration until @gregorwolf is back, he's much more experienced.

Do you have for SITHH a different code base or is it a branch of SITreg from Gregor ?

**Comment by RenaldWittwer** [comment] 2016-09-01 21:21
Hi Alex,

I think the solution is based on the SITHH, at least the idea. I don't know how much from the code is used, probably not that much.

As far as I can see a database migration is not needed. All needed values are available, it's all a matter of the UI.

I have two models, the registrationList and the waitingList. Both are copys from the registration, read from the database. In the registrationList I delete all entries that are bigger than the number of registration, in the waitingList I delete all entries that are smaller than the number of registration. 

The only thing that we need is to read the max number of participants.

You can see the result at http://www.sithh.de/sitlist , except the point that the waitingList is empty. 

I can provide the js Code and the XML of the view, but you can find it here: RenaldWittwer/SITApp/sitlist_GITGHUB  https://github.com/RenaldWittwer/SITApp/tree/master/sitlist_GITGHUB

Best regards
Renald

**Comment by chtcil** [comment] 2016-09-12 07:33
MaxAttendees is now fixed in Creation and the jasmine test are up and running (thx gregor!)
@RenaldWittwer thx for helping. We might can pimp the participant list with your help. 
So open points are now:
- Participantlist start the output count from 1 for the selected event, so it's better visible why someone is waiting (and also a waiting / non waiting list filter would be great)
- Update Procedure fixes is open now, so when an active participant cancels, then the longest waiting participant for that event get's active and notified
- Migration script, so that over-event-limit-participants get into waiting mode

**Comment by gregorwolf** [comment] 2016-09-14 20:20
Duplicate of #8

**Closed as completed by gregorwolf** 2016-09-14 20:20 UTC
